### PR TITLE
Some fixes on name resolution for fields.

### LINKED ISSUE #296: using `x` as a field name causes an compilation error
When `x` is used in the contract field, the compiler emits an error.
## PoC
Code:
```
import std;

contract PoC {
    x : word;
}
```
Error:
```
tcExp not implemented for: this.x
FieldAccess Nothing x
 - in:Typedef.rep(this.x)
 - in:function toWord (x : ?$5999) -> word {
   return Typedef.rep(this.x);
}
 - in:?$5999 : Add, ?$5999 : Sub, ?$5999 : Bounded, ?$5999 : Eq, ?$5999 : Ord, ?$5999 : Typedef (word) => default instance ?$5999 : Num {
   function maxVal () -> ?$5999 {
      return Bounded.maxVal();
   }
   function toWord (x : ?$5999) -> word {
      return Typedef.rep(this.x);
   }
   function fromWord (x : word) -> ?$5999 {
      return Typedef.abs(this.x);
   }
   function add (x : ?$5999, y : ?$5999) -> ?$5999 {
      return Add.add(this.x, y);
   }
   function sub (x : ?$5999, y : ?$5999) -> ?$5999 {
      return Sub.sub(this.x, y);
   }
   function gt (x : ?$5999, y : ?$5999) -> bool {
      return Ord.gt(this.x, y);
   }
}
```

If `x` is renamed to `x1`, for example, the compilation succeeds.

### PR DESCRIPTION
**Pull request by rodrigogribeiro**
This PR fixes #296 and #295.

### CODE REVIEW

File: src/Solcore/Pipeline/SolcorePipeline.hs [hunk 1]
```diff
@@ -66,14 +66,12 @@ compile opts = runExceptT $ do
...
 
   -- Name resolution
-  (resolved, nameEnv) <- ExceptT $ buildAST' parsed
+  resolved <- ExceptT $ nameResolution parsed
 
   liftIO $ when (verbose || optDumpAST opts) $ do
     putStrLn "> AST after name resolution"
     putStrLn $ pretty resolved
 
-  liftIO $ when (optDumpEnv opts) $ pPrint nameEnv
```
Comment (Y-Nak) [inline src/Solcore/Pipeline/SolcorePipeline.hs:75]: Now, `optDumpEnv` is not used. Probably, it'd be better to remove the flag from the CLI option.

File: src/Solcore/Frontend/Syntax/NameResolution.hs [hunk 2]
```diff
@@ -0,0 +1,702 @@
...
+      e1' <- resolve e1
+      e2' <- resolve e2
+      let fun = QualName (Name "Div") "div"
+      pure $ Call Nothing fun [e1', e2']
+  resolve (S.ExpModulo e1 e2) =
+    do
+      e1' <- resolve e1
+      e2' <- resolve e2
+      let fun = QualName (Name "Mod") "mod"
+      pure $ Call Nothing fun [e1', e2']
```
Comment (Y-Nak) [inline src/Solcore/Frontend/Syntax/NameResolution.hs:393]: Currently, there is no instance of `Mod`. So, probably it'd be better to add instance `word: Mod` at least in this PR.
code: 
```
import std;
function foo(x: word, y: word) -> word {
    return x % y;
}
```

result:
```
Cannot entail:
word : Mod
using defined instances:


 - in:function foo (x : word, y : word) -> word {
   return Mod.mod(x, y);
}
```

File: src/Solcore/Frontend/Syntax/NameResolution.hs [hunk 3]
```diff
@@ -0,0 +1,702 @@
...
+        (_, Just TParameter) -> pure (Var n)
+        -- field access
+        (Nothing, Just TField) ->
+          pure (FieldAccess Nothing n)
+        -- function reference
+        (_, Just TFunction) -> do
+          dt1 <- gets (Map.lookup n . fieldEnv)
+          case dt1 of
+            Just TField -> pure (FieldAccess Nothing n)
+            _ -> pure (Var n)
```
Comment (mbenke) [inline src/Solcore/Frontend/Syntax/NameResolution.hs:315]: Should fields have precedence over functions? Is there a way to call the function if there is a field with same name?

We should discuss it and maybe consider something like `this.field`

File: src/Solcore/Frontend/Syntax/NameResolution.hs [hunk 4]
```diff
@@ -0,0 +1,702 @@
...
+
+-- definition of an environment
+
+data DeclType
+  = TContract
+  | TFunction
+  | TDataCon
+  | TLocalVar
+  | TParameter
+  | TPattern
```
Comment (mbenke) [inline src/Solcore/Frontend/Syntax/NameResolution.hs:506]: What is this for? Pattern synonyms?

File: std/std.solc [hunk 5]
```diff
@@ -156,7 +156,6 @@ forall a. a:Ord =>
 function gt(x:a, y:a) -> bool {
   return Ord.gt(x,y);
 }
-
```
Comment (mbenke) [inline std/std.solc:159]: why remove this line?

File: src/Solcore/Frontend/Syntax/NameResolution.hs [hunk 6]
```diff
@@ -0,0 +1,702 @@
...
+        fdt = Map.lookup n (fieldEnv env)
+    pure (ldt <|> gdt <|> cdt <|> fdt)
+
+wrapError :: (Pretty b) => ResolveM a -> b -> ResolveM a
+wrapError m e =
+  catchError m handler
+  where
+    handler msg = throwError (decorate msg)
+    decorate msg = msg ++ "\n - in:" ++ pretty e
+
```
Comment (mbenke) [inline src/Solcore/Frontend/Syntax/NameResolution.hs:638]: This seems unused, do you plan to use it?

```suggestion
```

**Review by mbenke — COMMENTED** [review]
ElabTree should probably be removed from sol-core.cabal

File: src/Solcore/Frontend/Syntax/NameResolution.hs (hunk 3 above)
Comment (rodrigogribeiro) [reply src/Solcore/Frontend/Syntax/NameResolution.hs:315]: This ambiguity is what I said last week about using something like quoted names for functions or even use `this`. I must confess that I would prefer to use quotes... :)

File: src/Solcore/Frontend/Syntax/NameResolution.hs (hunk 4 above)
Comment (rodrigogribeiro) [reply src/Solcore/Frontend/Syntax/NameResolution.hs:506]: This is to identify when a name is introduced by a pattern matching.

File: src/Solcore/Frontend/Syntax/NameResolution.hs (hunk 6 above)
Comment (rodrigogribeiro) [reply src/Solcore/Frontend/Syntax/NameResolution.hs:638]: Currently, it is not used, but the error messages are crap. I intend to add `wrapError` to give context to error messages.

File: src/Solcore/Frontend/Syntax/NameResolution.hs (hunk 2 above)
Comment (rodrigogribeiro) [reply src/Solcore/Frontend/Syntax/NameResolution.hs:393]: Fixed by adding a instance for `word` in `std.solc`. Added the test suggested by @Y-Nak in the test suite.

File: std/std.solc (hunk 5 above)
Comment (rodrigogribeiro) [reply std/std.solc:159]: Added this empty line again and an additional instance for `word:Mod`.

File: src/Solcore/Pipeline/SolcorePipeline.hs (hunk 1 above)
Comment (rodrigogribeiro) [reply src/Solcore/Pipeline/SolcorePipeline.hs:75]: Removed from CLI options.

**Review by Y-Nak — APPROVED** [review]
LGTM!

File: src/Solcore/Frontend/Syntax/NameResolution.hs (hunk 6 above)
Comment (rodrigogribeiro) [reply src/Solcore/Frontend/Syntax/NameResolution.hs:638]: Added better error messages to name resolution.
