### PR TITLE
Fixes on instance typing

### LINKED ISSUE #189: overlapping instances accepted by compiler
The following snippet typechecks but should not (note the argument type to the methods for the `()` instance).

```
data uint256 = uint256(word);
forall self . class self:ABIAttribs {`
    function headSize(ty:Proxy(self)) -> word;
    function isStatic(ty:Proxy(self)) -> bool;
}

instance ():ABIAttribs {
    function headSize(ty : Proxy(uint256)) -> word { return 0; }
    function isStatic(ty : Proxy(uint256)) -> bool { return true; }
}
instance uint256:ABIAttribs {
    function headSize(ty : Proxy(uint256)) -> word { return 32; }
    function isStatic(ty : Proxy(uint256)) -> bool { return true; }
}
```

### PR DESCRIPTION
**Pull request by rodrigogribeiro**
This PR fixes #189, but it also found some problems on dispatch on std.solc.

### CODE REVIEW

File: test/Cases.hs [hunk 1]
```diff
@@ -10,7 +10,8 @@ std :: TestTree
 std =
   testGroup
     "Standard library"
-    [ runTestForFile "std.solc" stdFolder
+    -- this should work, but neet fix on the dispatch
+    [ runTestExpectingFailure "std.solc" stdFolder
```
Comment (d-xo) [inline test/Cases.hs]: the dispatch logic in std.solc is deleted in https://github.com/argotorg/solcore/pull/201 btw

**Comment by rodrigogribeiro** [comment]
> what was wrong with the previous implementation?

The problem is that type inference was not checking if the annotated type in the instance is compatible with its expected type. 
Since this was not checking, you could have something like:

```
forall a . class a: Foo {
    function foo (x : a) -> word;
}

instance word : Foo {
    function foo (x : word) -> word {
         return x;
    }
}

instance bool : Foo {
   function foo (x : word) -> word {
       return 0;
  }
}
```

The `bool` instance should be rejected since it is expected to have a function of type `bool -> word` and not `word -> word`, as it is currently annotated.

File: test/Cases.hs [hunk 2]
```diff
@@ -157,10 +158,10 @@ cases =
...
     , runTestForFile "word-match.solc" caseFolder
     , runTestForFile "if-examples.solc" caseFolder
-    , runTestForFile "import-std.solc" caseFolder
-    , runTestExpectingFailure "bound-minimal.solc" caseFolder
-    , runTestExpectingFailure "bound-only-test.solc" caseFolder
-    , runTestForFile "bound-with-pragma.solc" caseFolder
+    , runTestExpectingFailure "import-std.solc" caseFolder
+    , runTestExpectingFailure "withdraw.solc" caseFolder
+    , runTestForFile "bal.solc" caseFolder
+    , runTestForFile "if-examples.solc" caseFolder
```
Comment (d-xo) [inline test/Cases.hs]: why stop running the bound-X tests?

File: test/Cases.hs [hunk 3]
```diff
@@ -157,10 +158,10 @@ cases =
     , runTestForFile "uintdesugared.solc" caseFolder
     , runTestForFile "word-match.solc" caseFolder
     , runTestForFile "if-examples.solc" caseFolder
-    , runTestForFile "import-std.solc" caseFolder
```
Comment (d-xo) [inline test/Cases.hs:161]: why did this start failing?

File: test/Cases.hs (hunk 1 above)
Comment (d-xo) [inline test/Cases.hs]: can this be changed to pass again now the dispatch logic is removed?

File: test/examples/cases/instance-fun-typing.solc
Comment (d-xo) [inline test/examples/cases/instance-fun-typing.solc:1]: Ia this test being run in ci? I don't see it in Cases.hs

File: std/std.solc [hunk 4]
```diff
@@ -693,8 +693,8 @@ forall reader baseType reader baseType_decoded .baseType : ABIAttribs, reader:Wo
         let prx : Proxy(baseType_decoded);
         let result : memory(DynArray(baseType_decoded)) = allocateDynamicArray(prx, length);
         let offset = 0;
-        let prx : Proxy(baseType);
-        let elementHeadSize : word = ABIAttribs.headSize(prx);
+        // let prx : Proxy(baseType);
+        // let elementHeadSize : word = ABIAttribs.headSize(prx);
```
Comment (d-xo) [inline std/std.solc]: why?

File: test/examples/cases/mydispatch.solc
Comment (d-xo) [inline test/examples/cases/mydispatch.solc:1]: why do we need this file? can't we just merge the real std/dispatch.solc and test that? what is different here?

File: test/examples/cases/mystd.solc
Comment (d-xo) [inline test/examples/cases/mystd.solc:1]: what is different here vs std/std.sol. why do we need both?

File: test/Cases.hs [hunk 5]
```diff
@@ -167,8 +167,8 @@ cases =
     , runTestForFile "tuva.solc" caseFolder
     , runTestForFile "yul-return.solc" caseFolder
     , runTestForFile "pragma_merge_base.solc" caseFolder
-    , runTestForFile "pragma_merge_import.solc" caseFolder
-    , runTestForFile "pragma_merge_verify.solc" caseFolder
+    , runTestExpectingFailure "pragma_merge_import.solc" caseFolder
+    , runTestExpectingFailure "pragma_merge_verify.solc" caseFolder
```
Comment (d-xo) [inline test/Cases.hs]: why?

Comment (rodrigogribeiro) [reply test/Cases.hs]: The file `pragma_merge_import` does have overlapping instances:

```
forall X .
X : TestClassP2, X : TestClassP3, X : TestClassP4 => instance ImportType2 : TestClassP1 {
}
forall U .
U : TestClassP1, U : TestClassP2, U : TestClassP3 => instance U : TestClassP1 {
}
```
The same happens with `pragma_merge_verify.solc`.

File: test/examples/cases/mystd.solc
Comment (rodrigogribeiro) [reply test/examples/cases/mystd.solc:1]: I've added the files `mystd.solc` and `mydispatch.solc` to test the verification of the issue of accepting instances with the same head.

File: test/examples/cases/mydispatch.solc
Comment (rodrigogribeiro) [reply test/examples/cases/mydispatch.solc:1]: I've added the files mystd.solc and mydispatch.solc to test the verification of the issue of accepting instances with the same head.

File: std/std.solc (hunk 4 above)
Comment (rodrigogribeiro) [reply std/std.solc]: I commented these because they do not influence on the `result` of the function. Removing the comments, it will work just fine. I'll restore this to its previous state.

File: test/examples/cases/mydispatch.solc
Comment (d-xo) [reply test/examples/cases/mydispatch.solc:1]: can we replace them with some minimal test cases that cover the issue? these are going to be annoying to maintain going forward.

File: test/Cases.hs (hunk 5 above)
Comment (d-xo) [reply test/Cases.hs]: Ah, can we fix the tests so they no longer contain overlapping instances instead of just marking them as failing please?

File: test/examples/cases/mydispatch.solc
Comment (rodrigogribeiro) [reply test/examples/cases/mydispatch.solc:1]: Remove `mystd.solc` and `mydispatch.solc` and added a simple example.

File: test/Cases.hs (hunk 5 above)
Comment (rodrigogribeiro) [reply test/Cases.hs]: Fixed.

File: test/examples/cases/mystd.solc
Comment (rodrigogribeiro) [reply test/examples/cases/mystd.solc:1]: I removed both files and added a simple test case for overlapping.

File: test/examples/cases/pragma_merge_verify.solc [hunk 6]
```diff
@@ -7,7 +7,7 @@ import pragma_merge_base;
 data VerifyType(x) = VerifyType;
 
 // Would fail without imported pragma no-patterson-condition TestClassP1
-forall A . A:TestClassP1, A:TestClassP2, A:TestClassP3 => instance A:TestClassP1 {}
+forall A . A:TestClassP1, A:TestClassP2, A:TestClassP3 => instance VerifyType(A):TestClassP1 {}
```
Comment (mbenke) [inline test/examples/cases/pragma_merge_verify.solc]: This is OK wrt Paterson condition, so pointless as a test, also makes the comment above misleading.

File: test/examples/cases/pragma_merge_base.solc [hunk 7]
```diff
@@ -26,7 +26,7 @@ data TestType2 = TestType2;
 // --- Patterson Condition ---
 
 // Fails Patterson: Context measure (3 predicates) > conclusion measure (TestType1(U):TestClassP1)
-forall U . U:TestClassP1, U:TestClassP2, U:TestClassP3 => instance U:TestClassP1 {}
+forall U . U:TestClassP1, U:TestClassP2, U:TestClassP3 => instance (U,word):TestClassP1 {}
```
Comment (mbenke) [inline test/examples/cases/pragma_merge_base.solc]: This is OK wrt Paterson condition, so pointless as a test, also makes the comment above misleading.

Comment (mbenke) [inline test/examples/cases/pragma_merge_base.solc]:
```suggestion
// Fails Patterson: context constraint not smaller then head
forall U . (U,word):TestClassP1 => instance U:TestClassP1 {}
```

File: test/examples/cases/pragma_merge_verify.solc (hunk 6 above)
Comment (mbenke) [inline test/examples/cases/pragma_merge_verify.solc]:
```suggestion
// Would fail without imported pragma no-patterson-condition TestClassP3
forall A . word:TestClassP3 => instance A:TestClassP3 {}
```

..and add `TestClassP3` to the pragma (using TestClassP1 leads to overlapping)

**Comment by d-xo** [comment]
> > Can we also add a test for #189
> 
> I added a test case for that: `overlapping-heads.solc`

That seems to just test actual overlapping instances, and not cases where the instance sig is incorrect.
